//infrastack.ai environment variables
export const INFRASTACK_LOGS_ENABLED: string = "INFRASTACK_LOGS_ENABLED";
export const INFRASTACK_TAGS: string = "INFRASTACK_TAGS";
export const INFRASTACK_DEVELOPMENT_MODE: string =
  "INFRASTACK_DEVELOPMENT_MODE";
export const INFRASTACK_API_KEY: string = "INFRASTACK_API_KEY";
export const INFRASTACK_DISABLED_INSTRUMENTATIONS: string =
  "INFRASTACK_DISABLED_INSTRUMENTATIONS";
//opentelemetry environment variables
export const OTEL_EXPORTER_OTLP_ENDPOINT: string =
  "OTEL_EXPORTER_OTLP_ENDPOINT";
export const OTEL_EXPORTER_OTLP_HEADERS: string = "OTEL_EXPORTER_OTLP_HEADERS";
export const OTEL_EXPORTER_OTLP_PROTOCOL: string =
  "OTEL_EXPORTER_OTLP_PROTOCOL";
export const OTEL_SERVICE_NAME: string = "OTEL_SERVICE_NAME";
export const OTEL_SERVICE_VERSION: string = "OTEL_SERVICE_VERSION";
export const OTEL_SERVICE_INSTANCE_ID: string = "OTEL_SERVICE_INSTANCE_ID";
export const OTEL_K8S_NAMESPACE: string = "OTEL_K8S_NAMESPACE";
export const OTEL_K8S_POD_NAME: string = "OTEL_K8S_POD_NAME";
