name: Release npm package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/javascript/otel/**'

jobs:
  release:
    name: Release SDK to npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/javascript/otel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: packages/javascript/otel/package-lock.json
      
      - name: Install dependencies
        run: npm install
      
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          cwd: ./packages/javascript/otel
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}