name: Test Python package

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/python/otel/**'

jobs:
  build-and-test:
    name: Build and Test infrastackotel Package
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/python/otel

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]
          pip install pytest

      - name: Run Linter
        run: |
          pip install flake8
          flake8 . --ignore E501,W503

      - name: Run Tests
        env:
          INFRASTACK_TAGS: '[{"key": "env", "value": "test"}]'
        run: pytest

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Check distribution
        run: |
          pip install twine
          twine check dist/*
