//infrastack.ai environment variables
export const INFRASTACK_LOGS_ENABLED: string = 'INFRASTACK_LOGS_ENABLED';
export const INFRASTACK_TAGS : string = 'INFRASTACK_TAGS';
export const INFRASTACK_ENVIRONMENT : string = 'INFRASTACK_ENVIRONMENT';
export const INFRASTACK_INSTRUMENTATIONS : string = 'INFRASTACK_INSTRUMENTATIONS';
export const INFRASTACK_LLM_INCLUDE_PROMPTS : string = 'INFRASTACK_LLM_INCLUDE_PROMPTS';
export const INFRASTACK_SERVICE_NAME : string = 'INFRASTACK_SERVICE_NAME';
export const INFRASTACK_SERVICE_VERSION : string = 'INFRASTACK_SERVICE_VERSION';
export const INFRASTACK_POD_NAMESPACE : string = 'INFRASTACK_POD_NAMESPACE';
export const INFRASTACK_POD_NAME : string = 'INFRASTACK_POD_NAME';
export const INFRASTACK_ENVIRONMENT_ID : string = 'INFRASTACK_ENVIRONMENT_ID';

//opentelemetry environment variables
export const OTEL_EXPORTER_OTLP_ENDPOINT : string = 'OTEL_EXPORTER_OTLP_ENDPOINT';
export const OTEL_EXPORTER_OTLP_HEADERS : string = 'OTEL_EXPORTER_OTLP_HEADERS';


